//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otopark_Uygulmasi.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class araclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public araclar()
        {
            this.parkYeri = new HashSet<parkYeri>();
        }
    
        public int aracId { get; set; }
        public string aracPlaka { get; set; }
        public string aracMarka { get; set; }
        public string aracRenk { get; set; }
        public int kisiId { get; set; }
    
        public virtual kisiler kisiler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parkYeri> parkYeri { get; set; }
    }
}
