//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otopark_Uygulmasi.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class kisiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kisiler()
        {
            this.araclar = new HashSet<araclar>();
        }
    
        public int kisiId { get; set; }
        public string kisiTc { get; set; }
        public string kisiAd { get; set; }
        public string kisiSoyad { get; set; }
        public string kisiTelNo { get; set; }
        public string Adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<araclar> araclar { get; set; }
    }
}
