//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otopark_Uygulmasi.Models.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_otoparkEntities : DbContext
    {
        public db_otoparkEntities()
            : base("name=db_otoparkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<araclar> araclar { get; set; }
        public virtual DbSet<giris> giris { get; set; }
        public virtual DbSet<kisiler> kisiler { get; set; }
        public virtual DbSet<otoparklar> otoparklar { get; set; }
        public virtual DbSet<parkYeri> parkYeri { get; set; }
    }
}
