//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otopark_Uygulmasi.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class otoparklar
    {
        public int otoparkId { get; set; }
        public string otoparkAd { get; set; }
        public string otoparkSehir { get; set; }
    }
}
