//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otopark_Uygulmasi.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class parkYeri
    {
        public int parkId { get; set; }
        public string parkYeri1 { get; set; }
        public int aracId { get; set; }
    
        public virtual araclar araclar { get; set; }
    }
}
